# Generated by Django 3.0.3 on 2020-05-25 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc_profile_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=64)),
                ('d_dob', models.DateField()),
                ('d_address', models.CharField(max_length=128)),
                ('d_email', models.EmailField(max_length=254)),
                ('d_mobile', models.CharField(max_length=10)),
                ('d_anniversary', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='pat_profile_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=64)),
                ('p_dob', models.DateField()),
                ('p_address', models.CharField(max_length=128)),
                ('p_email', models.EmailField(max_length=254)),
                ('p_mobile', models.CharField(max_length=10)),
                ('p_anniversary', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='treatment_plan_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=128)),
                ('treatment_amount', models.IntegerField()),
                ('d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp_api.doc_profile_table')),
            ],
        ),
        migrations.CreateModel(
            name='pat_treatment_history_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('observations', models.CharField(max_length=64)),
                ('treatment_amount', models.IntegerField()),
                ('d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp_api.doc_profile_table')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp_api.pat_profile_table')),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp_api.treatment_plan_table')),
            ],
        ),
        migrations.CreateModel(
            name='med_profile_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_habbit', models.CharField(max_length=128)),
                ('p_level_of_higgins', models.CharField(max_length=64)),
                ('p_cosmetic_concern', models.CharField(max_length=128)),
                ('p_medical_history', models.CharField(max_length=1024)),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp_api.pat_profile_table')),
            ],
        ),
    ]
