# Generated by Django 3.0.3 on 2020-05-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcp_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med_profile_table',
            old_name='p_cosmatic_concern',
            new_name='p_cosmetic_concern',
        ),
        migrations.RenameField(
            model_name='med_profile_table',
            old_name='p_level_of_higine',
            new_name='p_level_of_higgins',
        ),
        migrations.RenameField(
            model_name='pat_profile_table',
            old_name='p_aniversary',
            new_name='p_anniversary',
        ),
    ]
