# Generated by Django 3.0.3 on 2020-08-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcp_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='Is_Visited',
            field=models.BooleanField(default=False),
        ),
    ]
